[package]
name = "rust_text_adventure"
version = "0.1.0"
authors = ["czfire"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
